### ISSUE TITLE
Display options not filtering correction

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#165]
`analyzer.display_options('count', verbose=True, filters=['Georgia', 'county', '2018 General', 'total contests'])` will show candidates as well as the contests themselves.

**Comment by sfsinger19103** [comment]
Also: Need option to choose all contests of a particular type in Choose Contest dropdown. E.g., "all GA congressional" in addition to "US House GA District 1, US House GA District 2, etc."

**Comment by sfsinger19103** [comment]
Related: I saw (but could not capture with screenshot technology I understand) in the scatterplot user flow a list of candidate names that had duplicates. Perhaps an artifact of including the primary contests in the general election? In any case, should be addressed.
