### ISSUE TITLE
Add contest names to scatter plot return value

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#175]
@sfsinger19103 currently we have:
- Jurisdiction
- subdivision type
- BallotName for each axis
- CountItemType for each axis
- Election for each axis

This ticket adds the contest name for each axis. Please update this ticket if you can think of anything else that's needed.

**Comment by sfsinger19103** [comment]
### Properties of the entire plot which should be in the title:
- Jurisdiction
- Subdivision type

### Properties of a single axis depend on what kind of count it is.
Votes for a single candidate:
- Election
- Contest
- BallotName
- CountItemType
- (optional) Party

Contest vote totals:
- Election
- Contest
- CountItemType

(We haven't talked about this one that I recall, but it would be nice to have) Votes for a single party in a single contest "group" (e.g., congressional):
- Election
- Contest Group
- CountItemType
- Party
(For example, user will be interested to look at all Georgia counties votes for Dem congressional candidates vs votes for Rep congressional candidates)

### More ideas:

Ballots cast
- Election
- CountItemType

Ballots cast by party
- Election
- CountItemType
- Party

Voter registration
- Date (or date proxy, such as Election)

Voter registration by party
- Date (or date proxy)
- Party

What else?

**Comment by ericmtsai** [comment]
CountItemType in a scatter plot is always total.

**Comment by sfsinger19103** [comment]
> CountItemType in a scatter plot is always total.
I disagree!

We offer counts limited to a particular count item type (e..g, absentee) in the dropdown menu, as we should.
![image](https://user-images.githubusercontent.com/14353822/95247409-ac462b00-07ca-11eb-8b96-87bb2c93c20c.png)

**Comment by sfsinger19103** [comment]
Great to have contest names on the scatterplot label for candidate totals! 

And now we need to take the redundant contest name *off* the label when we're looking at contest totals:
![image](https://user-images.githubusercontent.com/14353822/95377666-c00b9300-0897-11eb-8da5-a6a291beb307.png)

**Comment by ericmtsai** [comment]
Note to self: the changes to allow all votes by party will also need some cleaning up here. For example, check out the axis titles when this is run: `analyzer.scatter('Georgia', '2018 General', 'Party total', 'Republican state-house', '2018 General', 'Party total', 'Democratic state-house')`
