### ISSUE TITLE
RESOLVED (but needs a check): repeated 'none or unknown' in scatterplot dropdown

### ISSUE THREAD

**Issue by sfsinger19103** [ElectionDataAnalysis/election_data_analysis#201]
To recreate: in Compare Counts flow: Georgia/county/2018 General/candidate totals

Related: can't find Brian Kemp or Stacey Abrams in Georgia 2018 candidate list in Compare Counts flow

**Comment by sfsinger19103** [comment]
Probably closed in #204 but need to check.

**Comment by ericmtsai** [comment]
Confirmed that `none or unknown` only shows up once and the Stacy Abrams is found in the results.
