### ISSUE TITLE
Ordering of Candidates makes no sense

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#207]
When selecting candidates in the dropdowns for the scatter plot, the order is seemingly random, making it hard to select. The order is returned by the API, so we want to enforce an ordering by last name.

**Comment by sfsinger19103** [comment]
This is important, and we should talk about exactly what we want here. Might make more sense to list contest and/or party along with candidate name.

**Comment by ericmtsai** [comment]
<img width="294" alt="Screen Shot 2020-10-08 at 12 16 27 PM" src="https://user-images.githubusercontent.com/15315554/95508603-1ea04200-0968-11eb-8bd9-c2b79aea0551.png">

Primary contests don't need the party. IL Downstate United can be abbreviated DU. Order by contest first, then last name in reverse.
