### ISSUE TITLE
Dataloader throws error even though data is actually loaded. 

### ISSUE THREAD

**Issue by wonderbug2020** [ElectionDataAnalysis/election_data_analysis#235]
This is specifically for IL 2020 primary data. When loading the data using the typical process with the dataloader, I will get the return below. However, I have tested and verified this data, it even says it has been uploaded at the top. It also stops the program which is a problem in and of itself if you are trying to load multiple states at a time and a virtual nonissue interrupts the loading process. 

```
Processing IL_2020_prim.xls

        Results uploaded with munger il_pri to database Engine(postgresql://postgres:***@localhost:5432/EAD2)
from file E:\Vote_data\main_data\IL_2020_prim.xls
assuming jurisdiction E:\Voter_project_2\election_data_analysis\src\jurisdictions\Illinois
il20p.ini and its results file loaded successfully.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wolgy\anaconda3\lib\site-packages\election_data_analysis-1.0-py3.8.egg\election_data_analysis\__init__.py", line 242, in load_all
    err = ui.report(
  File "C:\Users\wolgy\anaconda3\lib\site-packages\election_data_analysis-1.0-py3.8.egg\election_data_analysis\user_interface\__init__.py", line 784, in report
    f.write(out_str)
  File "C:\Users\wolgy\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2554' in position 4576: character maps to <undefined>
```

**Comment by sfsinger19103** [comment]
Try changing the encoding to utf_8.

This may be an error that matters, as it may be missing a character in a candidate name.

In any case, the program should handle the issue more gracefully.

**Comment by sfsinger19103** [comment]
Looks like the culprit is in cell G65: 

ANDR╔
--

Never say "never" in elections, but I really doubt that the actual candidate's name is supposed to have that character in it.

**Comment by sfsinger19103** [comment]
https://ilga.gov/house/Rep.asp?MemberID=1536

**Comment by sfsinger19103** [comment]
He's on the ballot in November, [per BallotPedia](https://ballotpedia.org/Andre_Thapedi). (elections.il.gov was not functioning tonight)

**Comment by sfsinger19103** [comment]
@wonderbug2020 what's the status of this?

**Comment by wonderbug2020** [comment]
this might just be an issue on my system. It looks like the data has been loaded into the db based on the map @ericmtsai shared.

**Comment by sfsinger19103** [comment]
It's not just your system. Data loaded into the Visualizer db, but listed candidate "none or unknown" for House District 32-D.

**Comment by sfsinger19103** [comment]
I'll try to fix it now.
