### ISSUE TITLE
Update display labels for contest types

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#302]
Currently this pulls directly from the database labels. These are:
- congressional
- state
- state-house
- state-senate

Update these on the user facing side to make more sense to the user.

**Comment by ericmtsai** [comment]
@sfsinger19103 Do you have suggestions on a good re-labeling?

**Comment by sfsinger19103** [comment]
state -> statewide.

But since this means we have to do a mapping, let's capitalize pun intended

congressional ->  Congressional
state ->  Statewide
state-house -> State House
state-senate -> State Senate
