### ISSUE TITLE
Ensure all results.ini files use jurisdiction_directory

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#322]
Some are still using jurisdiction_path and pointing to local paths. Go through all files in [here](https://github.com/ElectionDataAnalysis/election_data_analysis/tree/main/src/ini_files_for_results) and update to use jurisdiction_directory.

**Comment by sfsinger19103** [comment]
Closed in commit 323f4d73a7db1569bd968474dac13361a360e60f (pushed directly to `main`, a mistake, but very few files and no code files were involved).
