### ISSUE TITLE
Arkansas loads vote types incorrectly

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#34]
Arkansas data loaded using [these materials](https://drive.google.com/drive/folders/12a2EkW8HGvpF8XYuALCuBytAKsLCMm6i) do not include votes with the label `totals`. Opening up the raw data files, note that "Total" is an available column. However, the resulting CountItemTypes in the database only include the following:
- absentee
- early
- election-day
- other
- provisional

From Stephanie:
Looking at a db with only AR data, I see five vote types, shown here with counts for one selection in one reporting unit:
- absentee,5
- early,7
- election-day,1090
- other,1280
- provisional,2382

So it seems, first of all, that the system is recognizing 'total' as 'other' -- not sure why. Also, I'm guessing that the categories are mislabeled, since 2382 is the sum of all the others, and so should be 'total'.

This causes #32

**Comment by sfsinger19103** [comment]
```Arkansas;Garland County,Senator Alan Clark,AR Senate District 13 (Republican Party),other,1280
Arkansas;Garland County,Senator Alan Clark,AR Senate District 13 (Republican Party),election-day,1090
Arkansas;Garland County,Senator Alan Clark,AR Senate District 13 (Republican Party),early,7
Arkansas;Garland County,Senator Alan Clark,AR Senate District 13 (Republican Party),absentee,5
Arkansas;Garland County,Senator Alan Clark,AR Senate District 13 (Republican Party),provisional,2382```

**Comment by sfsinger19103** [comment]
I'm guessing that the 'other' came from reading 'Registered Voters' as the first vote type. Problem is almost certainly in my munging code, where I drop the second column from the left. Perhaps I forgot to drop the second column header from the left.

**Comment by sfsinger19103** [comment]
@ericmtsai is this working now?

**Comment by ericmtsai** [comment]
@sfsinger19103 Yes, closing now
