### ISSUE TITLE
demote unused requirements

### ISSUE THREAD

**Issue by wstlabs** [ElectionDataAnalysis/election_data_analysis#37]
Ideally the `requirements.txt` should refer only to packages that are actually imported (or implied by imports):

Currently ours has the following entries which, last I checked, were not used anywhere:

`alembic==1.3.3
kiwisolver==1.1.0
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
six==1.14.0
easygui
xlrd
sqlalchemy_utils`

Having these in the `requirements.txt` has the effect of (1) slowing the build process and (2) impeding comprehension of the codebase as a whole. 

If the idea in putting them there was as a "memo" of sort about packages we're considering using at some point -- that's okay (in a way) but at the very least these entries should be commented.  Ideally there should be no "live" entries referencing packages not in actual current use.

**Comment by ericmtsai** [comment]
These can be deleted.

**Comment by ericmtsai** [comment]
Closed by #83
