### ISSUE TITLE
`Selection` table has `Id` column only

### ISSUE THREAD

**Issue by wstlabs** [ElectionDataAnalysis/election_data_analysis#39]
After running the PA-2018g model (using the setup in the in the `debug-PA-1` branch) we end up with a `Selection` table that has just as single column for the PK (and no other columns): 

```
select * from "Selection" limit 5;
  Id  
------
   59
   60
   61
 4774
 4775
```

Presumably this is not the intended functionality -- as it's hard to to see the purpose of joining on a table that contains no other information besides the primary key.

**Comment by sfsinger19103** [comment]
Selection is a parent to both CandidateSelection and BallotMeasureSelection. So the purpose of the Id-only table is to allow differentiation of Candidate- from BallotMeasure Selections when necessary, while allowing them to be treated in a unified way when appropriate. In the current implementation this inheritance is *not* in the schema, and that should be fixed.

**Comment by sfsinger19103** [comment]
See #53
