### ISSUE TITLE
Missing `ElectionDistrict` table

### ISSUE THREAD

**Issue by wstlabs** [ElectionDataAnalysis/election_data_analysis#40]
After running the PA-2018g model (using the setup in the in the `debug-PA-1` branch) we 
see that two tables - `Office` and `BallotMeasureContest` - have FK columns for the 
table `ElectionDistrict` - and these keys are even populated in the running database:

```
select * from "Office" limit 1;
  Id  |        Name         | Description | ElectionDistrict_Id 
------+---------------------+-------------+---------------------
 1080 | PA House District 1 |             |                 130

select * from "BallotMeasureContest" limit 1;
  Id  | ElectionDistrict_Id | Election_Id 
------+---------------------+-------------
 2825 |                 401 |        2824
```

Only problem is -- there's no such table (`ElectionDistrict`) present in the database.

**Comment by ericmtsai** [comment]
I believe this is ok as-is. The ElectionDistrict (either as a foreign key or semantically) points to a ReportingUnit. This is like saying, "The election district of <a particular contest> is <a particular county> in North Carolina".

Will see if @sfsinger19103 has any additional input, but I believe this issue can be closed.
