### ISSUE TITLE
Strange error after running `DataLoader.load_all()`

### ISSUE THREAD

**Issue by wstlabs** [ElectionDataAnalysis/election_data_analysis#43]
After running the PA-2018g model (using the setup in the in the `debug-PA-1` branch) we see the `err` dict contains the following cryptic (to us) entry:

```
err = {'pa18g.ini': {'pa_gen': None}}
```

This is worrisome, first because in theory there should be no errors - but even more so because we can't figure out what this message is supposed to mean.

Here's the full output transcript from that script:

```
python ../bin/load-all.py 
Loading jurisdiction from /opt/verify/src/jurisdictions/Pennsylvania to Engine(postgresql://verify:***@localhost:5432/eda2)
Processing results files ['pa18g.ini']
Processing Official_7232020043015PM.CSV
VoteCount load time in seconds: 2.8637200269999994
	Results uploaded with munger pa_gen to database Engine(postgresql://verify:***@localhost:5432/eda2)
from file /opt/verify/model/PA/data/2018g/Official_7232020043015PM.CSV
assuming jurisdiction /opt/verify/src/jurisdictions/Pennsylvania
	Archived pa18g.ini and its results file.
err = {'pa18g.ini': {'pa_gen': None}}
```

And here's that `load-all.py` script itself: 

```
import election_data_analysis as ea
an = ea.Analyzer()
dl = ea.DataLoader()
err = dl.load_all()
print(f"err = {err}")
```

**Comment by sfsinger19103** [comment]
Thanks for pointing out that this is confusing. In fact, this is indicating -- to the person who wrote the code, anyway -- that there is no error.
