### ISSUE TITLE
Add tests for NIST exports

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#502]
I've hand checked some of the NIST exports - making sure totals line up correctly, etc. But there doesn't seem to be a clean way to fit testing the exports into any existing testing scheme. This issue is meant to document the fact that there are no tests yet for the exports, and to explore the best way to add testing in before the exports go live.

**Comment by sfsinger19103** [comment]
Subsumed in #683
