### ISSUE TITLE
Fix broken mungers on new munging approach

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#507]
I tested all of 2020 and here are the broken ones. These look mostly like normal munging errors (the asserted values don't match what the code finds), except for MT and OR which had the errors that follow.
- AK 2020
- AZ 2020
- IN 2020
- MI 2020
- MN 2020
- MT 2020 : `Unable to pivot dataframe HD 035 STATE REPRESENTATIVE DI:  No objects to concatenate`
- NH 2020
- OK 2020
- OR 2020 `File errors (reload_Polk.csv): Unable to pivot dataframe Sheet1: No objects to concatenate`
- PA 2020
- TX 2020
- UT 2020
- VA 2020
- NC 2020

**Comment by sfsinger19103** [comment]
Looks like the issue is with the aux_data dictionary, which should be empty (unless there is actual aux data, like for NIST cdf or Michigan 2018 by precinct).

**Comment by ericmtsai** [comment]
Fixed on another branch.
