### ISSUE TITLE
Handle exceptions - juris file format checking 

### ISSUE THREAD

**Issue by Raghu-Srungavarapu** [ElectionDataAnalysis/election_data_analysis#540]
When the Juris file are not in proper format, the programs quits with no error reports. 
Example: When I opened Juris files on windows system, it added a weird character at the start of the file. Hence check against the template failed.

However no errors were reported and program had quit without any error report.

**Comment by Raghu-Srungavarapu** [comment]
No errors reported when the dictionary had 4 columns. The program would quit without any errors.

**Comment by sfsinger19103** [comment]
Juris file checks should include:

- [ ] dictionary should have no nulls in any field
- [ ] number of fields in each row should be correct for each file
- [ ] each element-raw_identifier pair (e.g., CandidateContest-President) should be unique within the dictionary file
- [ ] check encoding is default_encoding (constant defined in `election_data_analysis/__init__.py`)
- [ ] check consistency between files (might still be in there) and non-null conditions on elements
