### ISSUE TITLE
encoding issues UTF-8-BOM 

### ISSUE THREAD

**Issue by Raghu-Srungavarapu** [ElectionDataAnalysis/election_data_analysis#541]
When text files are opened/edited in windows, the files gets encoded to "UTF-8-BOM"
This type of files has invisible special character **_ï»¿_** at the beginning of the file. This causes issues while reading/comparing files using pandas read_csv

**Comment by sfsinger19103** [comment]
What editor are you using? [This post](https://stackoverflow.com/questions/8432584/how-can-i-make-notepad-to-save-text-in-utf-8-without-the-bom) suggests using the `Encoding → Encode in UTF-8 without BOM` feature of Notepad++. 

You might also experiment with emacs or vim.
