### ISSUE TITLE
Space between header and data in multi_block

### ISSUE THREAD

**Issue by toddgraham121** [ElectionDataAnalysis/election_data_analysis#654]
Nevada's data has a space between the header and the data that is likely causing an issue with reading the multiple blocks of data. 
![Screen Shot 2021-04-20 at 4 00 09 PM](https://user-images.githubusercontent.com/57152725/115474065-7c53f780-a1f1-11eb-8f7a-0e7a2382bc55.png)

**Comment by sfsinger19103** [comment]
For now, such cases will have to be addressed by revising the input file. This restriction is now in the documentation.
