### ISSUE TITLE
Exception occurred: 'child_id' when candidates aren't in dictionary/candidate txt files

### ISSUE THREAD

**Issue by toddgraham121** [ElectionDataAnalysis/election_data_analysis#659]
Ran into error `Exception occurred: 'child_id'` prior to adding the candidates for AS into the candidate.txt file and dictionary.txt file. There was no additional warnings that are populated in the .warning file to indicate the candidates are missing.

**Comment by sfsinger19103** [comment]
Also occurred when regex used regex {} notation (conflict with our  {} notation)
