### ISSUE TITLE
`assign_anomaly_score` should not crash when no CountItemType is 'total'

### ISSUE THREAD

**Issue by sfsinger19103** [ElectionDataAnalysis/election_data_analysis#70]

**Comment by ericmtsai** [comment]
This occurs [here](https://github.com/ElectionDataAnalysis/election_data_analysis/blob/aa1551801b098a29b955e490cc166b92def616c6/src/election_data_analysis/analyze/__init__.py#L395) if `total` is not found in the data. A fix is to use the sum of all `CountItemType`s not equal to `total` in place of filtering on `total`.

**Comment by ericmtsai** [comment]
Closed by PR #73
