### ISSUE TITLE
Proper naming convention for reporting unit

### ISSUE THREAD

**Issue by wonderbug2020** [ElectionDataAnalysis/election_data_analysis#75]
For the Reportingunit.txt and dictionary.txt jurisdiction files, the naming convention for counties should include the word county. For example, Indiana;Adams County as opposed to simply Indiana;Adams

**Comment by ericmtsai** [comment]
@wonderbug2020 I see these correctly, [see here](https://github.com/ElectionDataAnalysis/election_data_analysis/blob/6bff1bb976e7d744c5937abe41814cf216baaa65/src/jurisdictions/Indiana/ReportingUnit.txt#L162). Can you point to where this is a problem?

**Comment by wonderbug2020** [comment]
After going over the indiana files with Stephanie this was an issue raised where it could be a potential issue. This might be more of an opened ended reminder for those prepping jurisdiction files. Now that I think about it this might now be the best place for this issue.
