### ISSUE TITLE
Backfill tests for jurisdictions that are ready to go

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/election_data_analysis#85]
Jurisdictions that are ready to go are listed in our shared [google drive](https://drive.google.com/drive/folders/1el2TLqA50dq9RUYGX4Di5Rm5SubxBh8D). The states labeled `check` can be loaded into a DB and have tests written against that data. 

Tests are located at `election_data_analysis/tests/test_dataloader.py`. Each state will require at least 6 tests written. Please follow the naming convention with the existing North Carolina examples. Some tests are irrelevant for a particular jurisdiction when counts by vote type are not provided; for these, check the North Carolina examples and you can see an example of a test that is simply `assert True == True`. (We do this to demonstrate completeness of the tests and indicate that it's not simply a test that has been overlooked.)

The counts that the tests assert against should come from a manual (human) calculation out of the raw datafile. Essentially we are ensuring that the data gets loaded correctly and the aggregation occurs correctly.

You may need to do a `pip install pytest` to install the correct package to run these tests. Then, from the `tests` directory, simply run `pytest`.

**Comment by ericmtsai** [comment]
@bloy86 One more state to include: Michigan. All materials are in the shared drive to load these to a DB.

**Comment by sfsinger19103** [comment]
Tx @bloy86 !
