### ISSUE TITLE
(more than a comfortable amount of) repetition across config files

### ISSUE THREAD

**Issue by wstlabs** [ElectionDataAnalysis/election_data_analysis#97]
I doubt this is news to anyone - but there's definitely a lot of repetition of key directives across the various config files. 

For example, considering the 3 major `.ini` files for the PA configuration:

In both `pa18g.ini` and `jurisdiction_prep.ini`:
`munger_name=pa_gen`
`jurisdiction_path=/opt/verify/src/jurisdictions/Pennsylvania`
`results_file=/opt/verify/model/PA/data/2018g/Official_7232020043015PM.CSV`

And in both `jurisdiction_prep.ini` and `run_time.ini` we have:
`project_root=/opt/verify/src`

This are just obvious, "first-order" examples.  There are also cases of directives where we the variable names are different, even though they seem to be referring to the same thing - or are they?  It's not so easy to tell, e.g.:

`jurisdiction_prep.ini:name=Pennsylvania`
`pa18g.ini:top_reporting_unit=Pennsylvania`

And then there there cases of implicit repetition:  For example - we're pretty much *always* going to have the `jurisdictions` root directly under the `project_root` - and the state-level directory will hopefully *always* be named located directly under the the `jurisdictions` directory, and after the state[1] -- right?  In that case there's no need for a separate directive for the `jurisdiction_path`:

`jurisdiction_path=/opt/verify/src/jurisdictions/Pennsylvania`

BTW, I suppose that **some** of these repetitions may have a rationale -- but the point is there are *a lot* of repeated directives, and one can't *immediately* tell which have a purpose, and which are spurious.

I know these issues won't be fixed anytime soon - so I'm already applying the `low-priority` tag.  But they do add (unnecessary) confusion -- and in real terms, delay -- to the configuration process. 

[1] Actually, it should *always* be the 2-letter state code -- e.g. `jurisdictions/PA` - and not sometimes the 2-letter code, sometimes the full name like it is now.  But that's a separate issue.

**Comment by sfsinger19103** [comment]
Yes, this should be changed:

> In both pa18g.ini and jurisdiction_prep.ini:
munger_name=pa_gen
jurisdiction_path=/opt/verify/src/jurisdictions/Pennsylvania
results_file=/opt/verify/model/PA/data/2018g/Official_7232020043015PM.CSV

**Comment by sfsinger19103** [comment]
Addressed in #100:

> And in both jurisdiction_prep.ini and run_time.ini we have:
project_root=/opt/verify/src

**Comment by sfsinger19103** [comment]
The name of the jurisdiction directory may be different from the name of the top reporting unit. E.g., for NC the top reporting unit should be 'North Carolina' (the official name of the state) but a user may wish to use 'North-Carolina' for the jurisdiction directory name, or may have separate jurisdiction directories (perhaps for testing).

And, while users may use whatever convention they like for naming jurisdiction directories, our convention is to use the full name (to allow flexibility for, say, analyzing election results from the Philadelphia County Board of Elections by ward).

> jurisdiction_prep.ini:name=Pennsylvania
pa18g.ini:top_reporting_unit=Pennsylvania

In #100 names are perhaps clearer: 'jurisdiction_directory' and 'top_reporting_unit'

**Comment by sfsinger19103** [comment]
>  we're pretty much always going to have the jurisdictions root directly under the project_root

PR #100 gives the user flexibility to have jurisdiction and munger files outside the repo, and to specify these locations (along with all other variables related to the user's particular environment) in `run_time.ini`.
